Feacture/46 resumes list
fundev3/teamup-webapp pull request #20
Opened 2021-07-22 12:42 UTC by lina-ramirez-jalafund

2021-07-22 13:12 UTC, pedro-lima-jalafund commented
could you add AB#US format to link the user story with this Pr please

2021-07-22 13:34 UTC, pedro-lima-jalafund requested changes

2021-07-22 13:34 UTC, pedro-lima-jalafund commented on src/components/Resume/ResumeListApi.js
> +});
I think we do not need this anymore, since you are working with hard code `result`. Same for line 10

2021-07-22 13:34 UTC, pedro-lima-jalafund commented on src/components/Resume/ResumeListApi.js
> +    return errorRevise;
You can see how the values are returned from [this file](https://github.com/fundev3/teamup-webapp/blob/develop/src/components/Resume/ResumeDetail/useFetch.js), in that way wee can avoid the `.then` part on the return promise

2021-07-22 13:34 UTC, pedro-lima-jalafund commented on src/components/Resume/ResumeList.jsx
> +      .then(() => setResumes(list));
I guess is better to use `async, await` here?

2021-07-22 19:56 UTC, DaleneyRuben requested changes
Please @lina-ramirez-jalafund  update your branch with develop. so in the App component you can integrate your Resumes component
```
  ...
<Route component={Home} exact path="/"></Route>
<Route component={Resumes} exact path="/resumes">
  ...
``` 

btw the pipeline is failing please fix that

2021-07-26 20:55 UTC, niver-copa-jalafund approved these changes

2021-07-26 22:42 UTC, martin-callejas-jalafund commented
please resolve merge conflicts locally

2021-07-27 12:10 UTC, lina-ramirez-jalafund commented
> please resolve merge conflicts locally

I'm working on it

2021-07-27 12:11 UTC, closed without merging