Add route for project form
fundev3/teamup-webapp pull request #24
Opened 2021-07-22 21:37 UTC by freddy-perez-jalafund

AB#storynumber

# Overview

Add your Azure DevOps story number above to link to devops
Add general description explaining what this PR achieves

- e.g. Adds resume creation page

## Outstanding Tasks

- [ ] e.g. Integration with API

## Screenshots _(delete as appropriate)_

2021-07-23 23:03 UTC, niver-copa-jalafund approved these changes

2021-07-23 23:19 UTC, DaleneyRuben requested changes
Check latest changes on develop I've already added your component to the routes. 
EDIT: Please fulfill the pr template, linking your azure story and adding a description for this PR.

2021-07-26 22:42 UTC, martin-callejas-jalafund commented
please resolve conflicts locally

2021-07-27 17:09 UTC, closed without merging

2021-07-27 17:12 UTC, freddy-perez-jalafund commented
All the changes have been merged to start new tasks with the new changes and new features for tha reason it's not necessary to make this change (current branch feature/35-form-route-project) since they are ready in the develop branch.