Add Feature 162 integration api resume detail
fundev3/teamup-webapp pull request #42
Opened 2021-08-02 20:16 UTC by ela-ocana-jalafund

AB#162
https://dev.azure.com/funjaladev/DevLevel3/_boards/board/t/DevLevel3%20Team/Stories/?workitem=162
# Overview
- Review and adapt the PR with the new URLs, Integration with API, Integrate with Resume By id Component
- So that  TeamUp webapp should show information about resume of a person, as name, lastname, birthday, email, phone, 
address and summary.
- Show correct information about person resume. Integrations with API should show example data of teamUp repository.
Unit Test
## Outstanding Tasks

## Screenshots _(delete as appropriate)_
![imagen](https://user-images.githubusercontent.com/86006116/127918461-7ba63fc6-43d2-4725-be5f-87ef8c9cb9bc.png)

2021-08-02 21:38 UTC, rodrigo-baldiviezo-jalafund submitted a review, later dismissed
LGTM

2021-08-02 21:55 UTC, niver-copa-jalafund approved these changes, later dismissed

2021-08-03 04:36 UTC, jorge-lema-jalafund requested changes

2021-08-03 04:36 UTC, jorge-lema-jalafund commented on src/components/resumes/ResumesAPI.js
> +    console.log(result.statusText);
remove this console.log please

2021-08-03 04:36 UTC, jorge-lema-jalafund commented on src/components/resumes/ResumesAPI.js
>        "http://localhost:7071/api/resumes",
can you update this to follow our new pattern. 
![image](https://user-images.githubusercontent.com/85913826/127956234-898ffa15-4fe6-4ee0-b84c-d8386dbf018f.png)

2021-08-03 04:36 UTC, jorge-lema-jalafund commented on src/components/resumes/Details.jsx
> +            />
This field should be readOnly too

2021-08-03 04:36 UTC, jorge-lema-jalafund commented on src/components/resumes/Details.jsx
> +        <form autoComplete="off" className={classes.root} noValidate>
Could you improve the UI/UX a little? maybe Applying some styles to the fields when they are readonly or on edit mode? 
You could disable them or apply colors...or maybe change the variant of the component. It's up to you to decide :)

2021-08-03 04:36 UTC, jorge-lema-jalafund commented on src/components/resumes/Details.jsx
> +        <form autoComplete="off" className={classes.root} noValidate>
Please use Formik to validate and handle the form's data.

2021-08-04 17:54 UTC, niver-copa-jalafund approved these changes
Looks fine

2021-08-04 18:21 UTC, rodrigo-baldiviezo-jalafund approved these changes
LGTM

2021-08-04 18:52 UTC, jorge-lema-jalafund approved these changes
approved

2021-08-04 19:02 UTC, merged