Feature 225 / UI refactor for project list
fundev3/teamup-webapp pull request #44
Opened 2021-08-04 14:13 UTC by lilian-delgado-jalafund

AB#225

# Overview

Refactor UI Design: 
- Add search bar
- New format for project card
- New format for CreationDate

2021-08-04 18:49 UTC, jorge-lema-jalafund requested changes

2021-08-04 18:49 UTC, jorge-lema-jalafund commented on src/components/projects/Projects.jsx
> +              style={{ color: "#e2e2e2", fontSize: "10rem", margin: "30px" }}
can we change this for classes? check this
{ makeStyles } from '@material-ui/core/styles';
*Note:  for all those components on the updated files

2021-08-04 19:14 UTC, freddy-perez-jalafund commented on src/components/projects/Projects.jsx
> +            </Typography>
Suggestion change the phrase because it can be confused with a backend error

2021-08-04 20:10 UTC, jorge-lema-jalafund approved these changes
Approved!

2021-08-04 20:12 UTC, freddy-perez-jalafund approved these changes
Approved

2021-08-05 00:23 UTC, gustavo-rojas-jalafund approved these changes

2021-08-05 01:34 UTC, merged