Feature/33-Add components for projects list.
fundev3/teamup-webapp pull request #5
Opened 2021-07-15 19:14 UTC by ela-ocana-jalafund

It's feature/33
Frontend Projects List. 
It still need to consume the API, as it is not ready yet I would like you to review my components for a feedback

2021-07-15 21:09 UTC, martin-callejas-jalafund commented
please update with latest develop

we want to test the PR trigger and your branch is missing that file

2021-07-16 03:53 UTC, martin-callejas-jalafund commented on src/components/Project/Card.jsx
> +  //const { id, name, description, contact, creationDate } = props;
please remove this comment

2021-07-16 05:24 UTC, jorge-lema-jalafund requested changes
Solve the comment

2021-07-16 05:24 UTC, jorge-lema-jalafund commented on src/components/Project/ProjectsAPI.js
> +    console.log(error);
remove this console.log please
Handle the error and do or return something to let your component know that the API call failed. You could also handle the case when you get an empty list of projects.

2021-07-17 21:59 UTC, martin-callejas-jalafund commented
please cancel this PR and rename your branch, is not following our naming conventions... it reads: `Feuture/`
should be `feature/`

2021-07-17 22:27 UTC, closed without merging

2021-07-17 22:27 UTC, ela-ocana-jalafund commented
Rename branch.