Desing modal
fundev3/teamup-webapp pull request #68
Opened 2021-08-24 18:55 UTC by ela-ocana-jalafund

AB#375
https://dev.azure.com/funjaladev/DevLevel3/_backlogs/backlog/DevLevel3%20Team/Stories/?workitem=375

- Add an endpoint to get projects by skill name.
- Design a wireframe to show projects.
- Create a modal component to show projects.

## Outstanding Tasks
- [ ] e.g. Integration with API

2021-08-24 20:21 UTC, jorge-lema-jalafund requested changes

2021-08-24 20:21 UTC, jorge-lema-jalafund commented on src/components/projects/ProjectsAPI.js
> +    // TODO error handling
remove comment

2021-08-24 20:21 UTC, jorge-lema-jalafund commented on src/components/projects/ModalProjects.jsx
> +      // const projects = await getProjectsBySkill(searchProject);
what is this comment for?

2021-08-24 20:27 UTC, ela-ocana-jalafund commented on src/components/projects/ModalProjects.jsx
> +      // const projects = await getProjectsBySkill(searchProject);
At the moment I dont have endpoint

2021-08-25 17:35 UTC, rodrigo-baldiviezo-jalafund approved these changes

2021-08-25 19:48 UTC, pedro-lima-jalafund approved these changes
good job

2021-08-25 20:22 UTC, jorge-lema-jalafund approved these changes
approved

2021-08-25 20:25 UTC, merged