Feature/385 postulation UI
fundev3/teamup-webapp pull request #72
Opened 2021-08-25 16:31 UTC by ela-ocana-jalafund

AB#storynumber

# Overview

Add your Azure DevOps story number above to link to devops
Add general description explaining what this PR achieves

- e.g. Adds resume creation page

## Outstanding Tasks

- [ ] e.g. Integration with API

## Screenshots _(delete as appropriate)_

2021-08-26 18:49 UTC, jorge-lema-jalafund requested changes

2021-08-26 18:49 UTC, jorge-lema-jalafund commented on src/components/invitations/InvitationsModalResumes.jsx
> +      console.log(invitations);
remove console.log

2021-08-26 18:49 UTC, jorge-lema-jalafund commented on src/components/projects/ModalProjects.jsx
> +  const [send, setSend] = useState(false);
use   "ApplicationSent" instead of "Send". Since the past form of that verb is better to describe that state.

2021-08-26 18:49 UTC, jorge-lema-jalafund commented on src/components/projects/ModalProjects.jsx
> +  const sendProject = async (idResume, project) => {
sendProject isn't a good name for this function. SendApplication  or ApplyToProject  would be better names

2021-08-26 18:49 UTC, jorge-lema-jalafund commented on src/components/projects/ModalProjects.jsx
> +      resumeName: "Juan Gonzales",
why do we have this resumeName hardcoded

2021-08-26 22:04 UTC, ela-ocana-jalafund commented on src/components/projects/ModalProjects.jsx
> +      resumeName: "Juan Gonzales",
Is not a Hard code we need to send this data

2021-08-26 22:40 UTC, gustavo-rojas-jalafund submitted a review, later dismissed

2021-08-26 22:41 UTC, lilian-delgado-jalafund submitted a review, later dismissed

2021-08-27 02:04 UTC, alex-flores-jalafund approved these changes

2021-08-27 02:16 UTC, paola-quintanilla-jalafund approved these changes

2021-08-27 02:19 UTC, jorge-lema-jalafund approved these changes

2021-08-27 02:20 UTC, merged